package it.uniba.dib.sms2223_28.modello;

public enum Effect {
    NO_EFFECT,
    COPY_THIS_CARD,
    ADD_ATTACK_MY_TROOPS,
    TWO_HEAL_FOR_BEFORE_PLAYED_TROOPS,
    TWO_DAMAGE_FOR_BEFORE_PLAYED_TROOPS,
    COLOSSEUM,
    BRUTUS,
    SPARTACUS,
    NECROPOLIS,

    HEAL_FOR_OPPONENT_TROOPS,
    IMMORTALS,
    PERSIAN_BOW,
    ALEXANDER_THE_GREAT,
    SELEUCUS,
    CIRO,

    HYKSOS,
    PYRAMIDS,
    SHIP,
    CHEOPE,
    CHEFREN,


    X_DAMAGE,
    LEONIDA,
    IPPOCRATES,

    PHALANX,
    THERMOPYLAE,
    MENELAUS,
    GORGO
}
